### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by JosePedroDias** [jan-os/janos#1]
I own a peak just like you. Even used it as my phone for some time. I had the same desire to bypass the sandbox boot 2 gecko imposes. Your approach is crazy bold. Loved the video. Will. Flash mine asap. 
What reference did you use to get where you are? I found nothing relevant. Would rock if we could control opengles or even a dumb pixel buffer...

**Comment by janjongboom** [comment]
@JosePedroDias What do you mean 'which reference'? In general you can always shell out to Linux, although you need to write some code in Gecko to do that. But totally possible. In the end you can even create an `exec` function or something that you can call from JS. It's being done to control sensors anyway that way already. Have to recompile Gecko tho.
