### ISSUE TITLE
local_settings.json missing at default

### ISSUE THREAD

**Issue by blamot** [jan-os/janos#12]
After a clean install the bootstrap process fails (and so will the examples because of that) because there is no local_settings.json, there is a local_settings.json.example though. By renaming and doing a make install-phone the issue is resolved.

**Comment by janjongboom** [comment]
If there's no local_settings the system will warn you in the console (see https://github.com/jan-os/janos/blob/master/apps/system/js/bootstrap.js#L84), but it continues to boot (just doesn't know where to connect to WiFi, etc.). If your behavior is different, please reopen.
