### ISSUE TITLE
TCPSocket does not have permission in this context.

### ISSUE THREAD

**Issue by SunboX** [jan-os/janos#2]
First, thank you very much for this distro! :+1: 

If I'm running https://github.com/justindarc/fxos-web-server inside JanOS I'm getting:

```
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "TCPSocket does not have permission in this context.
" {file: "jar:file:///system/b2g/omni.ja!/components/TCPSocket.js" line: 647}]'[JavaScript Error: "TCPSocket does not have permission in this context.
" {file: "jar:file:///system/b2g/omni.ja!/components/TCPSocket.js" line: 647}]' when calling method: [nsIDOMTCPSocket::listen]
```

I've added the right permission to `https://github.com/janjongboom/janos/blob/master/apps/system/manifest.webapp`:

``` json
"permissions": {
    "tcp-socket": {}
},
```

So what's wrong with it?

**Comment by SunboX** [comment]
On which FxOS version is JanOS based? Maybe it doesn't really support `navigator.mozTCPSocket.listen`?

**Comment by janjongboom** [comment]
Hey @SunboX, it depends on the Gecko version you run on. listen should be included from Gecko 26.  What's the device you were running on? If it's geeksphone, grab one of their builds from http://downloads.geeksphone.com/, unzip it and then run:

```
adb reboot bootloader
fastboot flash boot boot.img
fastboot flash system system.img
fastboot erase cache
fastboot reboot
```

To only update Gecko, your code will keep on running.

I'll make some docs about this as well.
