### ISSUE TITLE
Geekphone Revolution update ?

### ISSUE THREAD

**Issue by fcarlier** [jan-os/janos#7]
Hello,

Can you submit a new support of janos with geekphone revolution ?
It's very har to buy a peak or keon phone ;)

Félicitations pour le travail ;)
F.

**Comment by janjongboom** [comment]
Hey, as far as I know the geeksphone revolution does not come with an up to date kernel so I don't think anyone can build new versions for it. Someone made a ZTE Open C build already and I made a Raspberry Pi build, hope to get it up this week.

**Comment by fcarlier** [comment]
damage, but the geekphone peak or keon are no longer for sale. Work on the raspberry is the reverse of your conference ;) I will continue to follow your other phones support ;)

**Comment by fcarlier** [comment]
Have you an example process for intall JanOs into ZTE open C ? THX

**Comment by janjongboom** [comment]
@fcarlier Yeah, I have a build that a community member made, need to test it this week.

**Comment by fcarlier** [comment]
@janjongboom Okay, i receive my ZTE Open C, the next week ;)

After, i can test your installation process if you want ;

**Comment by fcarlier** [comment]
@janjongboom I Have my beautiful ZTE Open C for testing :) ;)

**Comment by janjongboom** [comment]
@fcarlier Did you root it yet?

**Comment by manelboukthir** [comment]
@janjongboom Hello i'm fcarlier's colleague I have rooted the phone and installed the ready made build for zte open c.

I've tested the device motion and security cam examples, but i'm having a liitle trouble with the doorbell.

Could you please advise on how to force the pairing between the phone and the computer?

**Comment by janjongboom** [comment]
@manelboukthir Doorbell example needs a Bluetooth speaker. Does the speaker show up when running `window.findBluetoothDevices();` ?

**Comment by manelboukthir** [comment]
@jangjongboom I've tried it on my computer speaker and shows up when search for it but it fails pairing.

Do I need a dedicated Bluetooth speaker?

**Comment by manelboukthir** [comment]
@janjongboom I've tried it on my computer speaker and shows up when search for it but it fails pairing.

Do I need a dedicated Bluetooth speaker?

**Comment by janjongboom** [comment]
@manelboukthir I wrote the example for a dedicated bluetooth speaker yes (see https://youtu.be/Uy062kp-LM4?t=18m18s) I don't think a computer can broadcast itself as bluetooth speaker.

**Comment by manelboukthir** [comment]
@janjongboom : Thank you a lot for your answer i will try that with a proper bluetooth speeker.
I've also tested the briantracker  and it seems that the push server you put in place is down, since i get a Timeout error when i try to register.

Do you have any thoughts?

Thank you

**Comment by janjongboom** [comment]
@manelboukthir Hi, the server I have at janjongboom.com:1339 is still there. Maybe Mozilla changed something regarding their push servers, let me check on my Open C...

**Comment by janjongboom** [comment]
@manelboukthir Try registering a few times, at some point I managed to get through. What the hell is happening here, no clue...
